# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FYEO' do
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

# Pods for FYEO

pod 'FaceSDK'
pod 'FaceCoreMatch' # Required for offline/local matching


target 'FYEOTests' do
inherit! :search_paths
# Pods for testing


end

target 'FYEOUITests' do
# Pods for testing


end

end
